version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/backend

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh # ✅ 기존 폴더 정리 스크립트 추가
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
