name: Build & Push frontend Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Build Docker Image
        run: |
          cd frontend
          docker build -t my-frontend-app:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my-frontend-app:latest ${{ secrets.DOCKER_USERNAME }}/my-frontend-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-frontend-app:latest
